// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EJG69yLW_OoD0JypV0P8VynI3jFkZlw',
    appId: '1:626588113146:web:6cf60d13090f9263b25143',
    messagingSenderId: '626588113146',
    projectId: 'finalproject-c18b4',
    authDomain: 'finalproject-c18b4.firebaseapp.com',
    storageBucket: 'finalproject-c18b4.firebasestorage.app',
    measurementId: 'G-DHXGMJ7Q5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpn8purEp_H_puKdAWNz2VP9vOBcVDDsw',
    appId: '1:626588113146:android:ef3366811ed8e857b25143',
    messagingSenderId: '626588113146',
    projectId: 'finalproject-c18b4',
    storageBucket: 'finalproject-c18b4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5EJG69yLW_OoD0JypV0P8VynI3jFkZlw',
    appId: '1:626588113146:web:d6fe5368866f91efb25143',
    messagingSenderId: '626588113146',
    projectId: 'finalproject-c18b4',
    authDomain: 'finalproject-c18b4.firebaseapp.com',
    storageBucket: 'finalproject-c18b4.firebasestorage.app',
    measurementId: 'G-76J66DLH56',
  );
}
